#!/bin/bash

echo "🔧 Fixing 404 errors and payment session issue..."

# Fix 1: Create placeholder pages for missing routes
echo "Creating placeholder pages for missing routes..."

# Create customers page
mkdir -p app/customers
cat > app/customers/page.tsx << 'EOF'
export default function CustomersPage() {
  return (
    <div className="min-h-screen bg-gray-50 p-8">
      <div className="max-w-7xl mx-auto">
        <h1 className="text-2xl font-bold text-gray-900 mb-4">Customers</h1>
        <p className="text-gray-600">Coming soon...</p>
      </div>
    </div>
  )
}
EOF

# Create invoices page
mkdir -p app/invoices
cat > app/invoices/page.tsx << 'EOF'
export default function InvoicesPage() {
  return (
    <div className="min-h-screen bg-gray-50 p-8">
      <div className="max-w-7xl mx-auto">
        <h1 className="text-2xl font-bold text-gray-900 mb-4">Invoices</h1>
        <p className="text-gray-600">Coming soon...</p>
      </div>
    </div>
  )
}
EOF

# Create jobs page
mkdir -p app/jobs
cat > app/jobs/page.tsx << 'EOF'
export default function JobsPage() {
  return (
    <div className="min-h-screen bg-gray-50 p-8">
      <div className="max-w-7xl mx-auto">
        <h1 className="text-2xl font-bold text-gray-900 mb-4">Jobs</h1>
        <p className="text-gray-600">Coming soon...</p>
      </div>
    </div>
  )
}
EOF

# Fix 2: Debug and fix the payment API response
echo "Fixing payment API to return session ID correctly..."

# Create a temporary fix file to properly handle the Stripe session
cat > fix-payment-api.js << 'EOF'
const fs = require('fs');
const content = fs.readFileSync('app/api/create-payment/route.ts', 'utf8');

// Ensure we're returning the session ID correctly
let fixed = content;

// Make sure we're creating the session correctly
if (!fixed.includes('console.log(\'Created Stripe session:\', session.id)')) {
  fixed = fixed.replace(
    /const session = await stripe\.checkout\.sessions\.create\({/g,
    'const session = await stripe.checkout.sessions.create({'
  );
  
  fixed = fixed.replace(
    /return NextResponse\.json\({ sessionId: session\.id }\)/g,
    `console.log('Created Stripe session:', session.id);
    
    if (!session.id) {
      console.error('No session ID generated by Stripe');
      return NextResponse.json(
        { error: 'Failed to create payment session' },
        { status: 500 }
      );
    }
    
    return NextResponse.json({ sessionId: session.id })`
  );
}

// Add better error handling
fixed = fixed.replace(
  /} catch \(error: any\) {/g,
  `} catch (error: any) {
    console.error('Stripe error:', error);
    console.error('Error type:', error.type);
    console.error('Error message:', error.message);
    
    // Check for specific Stripe errors
    if (error.type === 'StripeInvalidRequestError') {
      return NextResponse.json(
        { error: \`Stripe configuration error: \${error.message}\` },
        { status: 400 }
      );
    }`
);

fs.writeFileSync('app/api/create-payment/route.ts', fixed);
EOF

node fix-payment-api.js
rm fix-payment-api.js

# Fix 3: Ensure success and cancel URLs are absolute
perl -i -pe "s|success_url: '/proposal/payment-success|success_url: \`\${process.env.NEXT_PUBLIC_BASE_URL || 'https://my-dashboard-app-tau.vercel.app'}/proposal/payment-success|g" app/api/create-payment/route.ts
perl -i -pe "s|cancel_url: '/proposal/view/|cancel_url: \`\${process.env.NEXT_PUBLIC_BASE_URL || 'https://my-dashboard-app-tau.vercel.app'}/proposal/view/|g" app/api/create-payment/route.ts

# Commit changes
git add .
git commit -m "fix: create missing pages and fix payment session response

- Add placeholder pages for customers, invoices, jobs
- Fix payment API to properly return session ID
- Add detailed Stripe error logging
- Use absolute URLs for Stripe success/cancel redirects"

git push origin main

echo "✅ Fixed 404 errors and improved payment handling!"
echo ""
echo "📝 What was fixed:"
echo "1. Created placeholder pages for Customers, Invoices, Jobs"
echo "2. Added session ID validation in payment API"
echo "3. Improved Stripe error messages"
echo "4. Fixed redirect URLs to be absolute"
echo ""
echo "⚠️ Check Vercel logs for Stripe-specific errors"
echo "Common issues:"
echo "- Product/Price not created in Stripe dashboard"
echo "- URLs not matching Stripe allowed domains"
echo "- API keys not matching (test vs live)"